/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpax.massis.sh3d.plugins.design;

import java.io.FileNotFoundException;
import java.io.IOException;

import rpax.massis.sh3d.plugins.MASSISPlugin;
import rpax.massis.sh3d.plugins.metadata.MASSISHomeMetadataManager;

import com.eteks.sweethome3d.model.Home;
import com.eteks.sweethome3d.model.RecorderException;

/**
 *
 * @author rpax
 */
@SuppressWarnings("all")
public class DesignerToolsFrame extends javax.swing.JFrame {

   
	private static final long serialVersionUID = 1L;
	
	
	
	
	private DesignerLog log;

	private Home home;
	/**
     * Creates new form DesignerToolsFrame
     */
    public DesignerToolsFrame() {
        initComponents();
        afterInit();
    }
    public DesignerToolsFrame(Home home) {
        initComponents();
        this.home=home;
        afterInit();
    }
    
    private void afterInit() {
    	System.gc();
    	this.log=new DesignerLog() {
			
			public DesignerLog clear() {
				textAreaLog.setText("");
				return this;
			}
			
			public DesignerLog appendLine(String str) {
				textAreaLog.append(str);
				textAreaLog.append("\n");
				return this;
			}
			
			public DesignerLog append(String str) {
				textAreaLog.append(str);
				return this;
			}
		};
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        static_label_designer_tools = new javax.swing.JLabel();
        scrollPaneLog = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        tabsPane = new javax.swing.JTabbedPane();
        invisibleWallsPanel = new javax.swing.JPanel();
        btnRUNInvisibleWalls = new javax.swing.JButton();
        changeAllRoomsColorPanel = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        btnRUNChangeRoomsColor = new javax.swing.JButton();
        testsIDPanel = new javax.swing.JPanel();
        btnCreateIDs = new javax.swing.JButton();
        btnCheckSavedIDs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        static_label_designer_tools.setText("Designer Tools");

        textAreaLog.setColumns(20);
        textAreaLog.setRows(5);
        scrollPaneLog.setViewportView(textAreaLog);

        btnRUNInvisibleWalls.setText("RUN");
        btnRUNInvisibleWalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUNInvisibleWallsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invisibleWallsPanelLayout = new javax.swing.GroupLayout(invisibleWallsPanel);
        invisibleWallsPanel.setLayout(invisibleWallsPanelLayout);
        invisibleWallsPanelLayout.setHorizontalGroup(
            invisibleWallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invisibleWallsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRUNInvisibleWalls, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        invisibleWallsPanelLayout.setVerticalGroup(
            invisibleWallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invisibleWallsPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnRUNInvisibleWalls)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        tabsPane.addTab("Invisible Walls", invisibleWallsPanel);

        btnRUNChangeRoomsColor.setText("RUN");
        btnRUNChangeRoomsColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUNChangeRoomsColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeAllRoomsColorPanelLayout = new javax.swing.GroupLayout(changeAllRoomsColorPanel);
        changeAllRoomsColorPanel.setLayout(changeAllRoomsColorPanelLayout);
        changeAllRoomsColorPanelLayout.setHorizontalGroup(
            changeAllRoomsColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeAllRoomsColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeAllRoomsColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRUNChangeRoomsColor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        changeAllRoomsColorPanelLayout.setVerticalGroup(
            changeAllRoomsColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeAllRoomsColorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRUNChangeRoomsColor))
        );

        tabsPane.addTab("Rooms Color", changeAllRoomsColorPanel);

        btnCreateIDs.setText("Create IDs");
        btnCreateIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIDsActionPerformed(evt);
            }
        });

        btnCheckSavedIDs.setText("Check saved IDS");
        btnCheckSavedIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckSavedIDsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testsIDPanelLayout = new javax.swing.GroupLayout(testsIDPanel);
        testsIDPanel.setLayout(testsIDPanelLayout);
        testsIDPanelLayout.setHorizontalGroup(
            testsIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testsIDPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCreateIDs)
                .addGap(127, 127, 127)
                .addComponent(btnCheckSavedIDs)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        testsIDPanelLayout.setVerticalGroup(
            testsIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testsIDPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(testsIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateIDs)
                    .addComponent(btnCheckSavedIDs))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        tabsPane.addTab("Tests ID", testsIDPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabsPane)
                    .addComponent(scrollPaneLog, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(static_label_designer_tools)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(static_label_designer_tools)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabsPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneLog, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRUNInvisibleWallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUNInvisibleWallsActionPerformed
    	DesignTools.makeOuterWallsInvisible(home,log );
    	
    	
    	
    }//GEN-LAST:event_btnRUNInvisibleWallsActionPerformed

    private void btnRUNChangeRoomsColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUNChangeRoomsColorActionPerformed
     
    }//GEN-LAST:event_btnRUNChangeRoomsColorActionPerformed

    private void btnCreateIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIDsActionPerformed
    	home.setVisualProperty(MASSISHomeMetadataManager.HOME_METADATA_MANAGER_KEY, null);
    }//GEN-LAST:event_btnCreateIDsActionPerformed

    private void btnCheckSavedIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckSavedIDsActionPerformed
        DesignTools.showHomeIDData(home,log);
    }//GEN-LAST:event_btnCheckSavedIDsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignerToolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignerToolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignerToolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignerToolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignerToolsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckSavedIDs;
    private javax.swing.JButton btnCreateIDs;
    private javax.swing.JButton btnRUNChangeRoomsColor;
    private javax.swing.JButton btnRUNInvisibleWalls;
    private javax.swing.JPanel changeAllRoomsColorPanel;
    private javax.swing.JPanel invisibleWallsPanel;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JScrollPane scrollPaneLog;
    private javax.swing.JLabel static_label_designer_tools;
    private javax.swing.JTabbedPane tabsPane;
    private javax.swing.JPanel testsIDPanel;
    private javax.swing.JTextArea textAreaLog;
    // End of variables declaration//GEN-END:variables
}
