/* Generated By:JavaCC: Do not edit this line. ShadyParserConstants.java */
package cz.cuni.amis.pogamut.shady;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShadyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int GE = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int NE = 15;
  /** RegularExpression Id. */
  int LE = 16;
  /** RegularExpression Id. */
  int LT = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int PART_LETTER = 20;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 21;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 22;
  /** RegularExpression Id. */
  int EXPONENT = 23;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 24;
  /** RegularExpression Id. */
  int STRING_LITERAL = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"node\"",
    "\"(\"",
    "\")\"",
    "\"and\"",
    "\"not\"",
    "\"or\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\".\"",
  };

}
