/* Generated By:JavaCC: Do not edit this line. PoshParserConstants.java */
package cz.cuni.amis.pogamut.sposh.elements;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PoshParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int LBRACE = 6;
  /** RegularExpression Id. */
  int RBRACE = 7;
  /** RegularExpression Id. */
  int DC = 8;
  /** RegularExpression Id. */
  int AP = 9;
  /** RegularExpression Id. */
  int AD = 10;
  /** RegularExpression Id. */
  int COMPETENCE = 11;
  /** RegularExpression Id. */
  int ELEMENTS = 12;
  /** RegularExpression Id. */
  int GOAL = 13;
  /** RegularExpression Id. */
  int HOURS = 14;
  /** RegularExpression Id. */
  int MINUTES = 15;
  /** RegularExpression Id. */
  int SECONDS = 16;
  /** RegularExpression Id. */
  int HZ = 17;
  /** RegularExpression Id. */
  int PM = 18;
  /** RegularExpression Id. */
  int NONE = 19;
  /** RegularExpression Id. */
  int TRIGGER = 20;
  /** RegularExpression Id. */
  int NIL = 21;
  /** RegularExpression Id. */
  int DRIVES = 22;
  /** RegularExpression Id. */
  int DOCUMENTATION = 23;
  /** RegularExpression Id. */
  int VARS = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int EQUAL_SIGN = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int PREDICATE = 29;
  /** RegularExpression Id. */
  int NUMFLOAT = 30;
  /** RegularExpression Id. */
  int NUMINT = 31;
  /** RegularExpression Id. */
  int NAME = 32;
  /** RegularExpression Id. */
  int JAVA_IDENTIFIER = 33;
  /** RegularExpression Id. */
  int ENUM_VALUE = 34;
  /** RegularExpression Id. */
  int COMMENT = 35;
  /** RegularExpression Id. */
  int VARIABLE = 36;
  /** RegularExpression Id. */
  int ERROR_CHARS = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "<DC>",
    "\"AP\"",
    "\"AD\"",
    "\"C\"",
    "\"elements\"",
    "\"goal\"",
    "\"hours\"",
    "\"minutes\"",
    "\"seconds\"",
    "\"hz\"",
    "\"pm\"",
    "\"none\"",
    "\"trigger\"",
    "\"nil\"",
    "\"drives\"",
    "\"documentation\"",
    "\"vars\"",
    "\",\"",
    "\"=\"",
    "\"true\"",
    "\"false\"",
    "<PREDICATE>",
    "<NUMFLOAT>",
    "<NUMINT>",
    "<NAME>",
    "<JAVA_IDENTIFIER>",
    "<ENUM_VALUE>",
    "<COMMENT>",
    "<VARIABLE>",
    "<ERROR_CHARS>",
  };

}
