/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.massisframework.testdata.gui;

import java.util.Arrays;
import java.util.List;

import javax.swing.ImageIcon;

/**
 *
 * @author rpax
 */
@SuppressWarnings("serial")
public class SampleHomesGUI extends javax.swing.JFrame {
	private final SampleHomeGUIControl control;

	/**
	 * Creates new form SampleHomesGUI
	 */
	public SampleHomesGUI()
	{
		this.control = null;
		initComponents();
		this.setHomeListValues(Arrays.asList("a", "b", "c", "d"));
	}

	public SampleHomesGUI(SampleHomeGUIControl control)
	{
		this.control = control;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.sampleHomesPanel = new javax.swing.JPanel();
		this.sampleHomesScrollPane = new javax.swing.JScrollPane();
		this.sampleHomesList = new javax.swing.JList<String>();
		this.jLabel1 = new javax.swing.JLabel();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.HomeDescriptionTextArea = new javax.swing.JTextArea();
		this.loadHomeButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Load sample home");

		this.sampleHomesList
				.setModel(new javax.swing.AbstractListModel<String>() {
					String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
							"Item 5" };

					@Override
					public int getSize()
					{
						return this.strings.length;
					}

					@Override
					public String getElementAt(int i)
					{
						return this.strings[i];
					}
				});
		this.sampleHomesList.setSelectionMode(
				javax.swing.ListSelectionModel.SINGLE_SELECTION);
		this.sampleHomesList.addListSelectionListener(
				new javax.swing.event.ListSelectionListener() {
					@Override
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt)
					{
						sampleHomesListValueChanged(evt);
					}
				});
		this.sampleHomesScrollPane.setViewportView(this.sampleHomesList);

		this.jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		this.jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/massisframework/testdata/gui/previewnotavailable.png"))); // NOI18N
		this.jLabel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		this.HomeDescriptionTextArea.setColumns(20);
		this.HomeDescriptionTextArea.setLineWrap(true);
		this.HomeDescriptionTextArea.setRows(5);
		this.jScrollPane1.setViewportView(this.HomeDescriptionTextArea);

		this.loadHomeButton.setText("Load home");
		this.loadHomeButton
				.addActionListener(new java.awt.event.ActionListener() {
					@Override
					public void actionPerformed(java.awt.event.ActionEvent evt)
					{
						loadHomeButtonActionPerformed(evt);
					}
				});

		final javax.swing.GroupLayout sampleHomesPanelLayout = new javax.swing.GroupLayout(
				this.sampleHomesPanel);
		this.sampleHomesPanel.setLayout(sampleHomesPanelLayout);
		sampleHomesPanelLayout.setHorizontalGroup(
				sampleHomesPanelLayout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(sampleHomesPanelLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(sampleHomesPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
										.addComponent(
												this.sampleHomesScrollPane)
										.addComponent(this.loadHomeButton,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												164, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(this.jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										256,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(this.jLabel1)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		sampleHomesPanelLayout.setVerticalGroup(
				sampleHomesPanelLayout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								sampleHomesPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addGroup(sampleHomesPanelLayout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														false)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														sampleHomesPanelLayout
																.createSequentialGroup()
																.addComponent(
																		this.sampleHomesScrollPane,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		0,
																		Short.MAX_VALUE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		this.loadHomeButton))
												.addComponent(this.jScrollPane1,
														javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(this.jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														257,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(44, Short.MAX_VALUE)));

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(this.sampleHomesPanel,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(this.sampleHomesPanel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void loadHomeButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_loadHomeButtonActionPerformed
		if (this.control != null)
		{
			this.control.loadHomeButtonActionPerformed(this, evt);
		}
	}// GEN-LAST:event_loadHomeButtonActionPerformed

	private void sampleHomesListValueChanged(
			javax.swing.event.ListSelectionEvent evt)
	{// GEN-FIRST:event_sampleHomesListValueChanged
		if (this.control != null)
		{
			this.control.sampleHomesListValueChanged(this, evt);
		}
	}// GEN-LAST:event_sampleHomesListValueChanged

	public void setDescription(String description)
	{
		this.HomeDescriptionTextArea.setText(description);
	}

	public void setImage(ImageIcon image)
	{
		this.jLabel1.setIcon(image);
	}

	public void setHomeListValues(final List<String> values)
	{

		this.sampleHomesList
				.setModel(new javax.swing.AbstractListModel<String>() {
					@Override
					public int getSize()
					{
						return values.size();
					}

					@Override
					public String getElementAt(int i)
					{
						return values.get(i);
					}
				});
		this.sampleHomesList.setSelectedIndex(0);
	}

	public String getSelectedHomeName()
	{
		return String
				.valueOf(this.sampleHomesList.getSelectedValue());
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try
		{
			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (final ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(SampleHomesGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(SampleHomesGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(SampleHomesGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(SampleHomesGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run()
			{
				new SampleHomesGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextArea HomeDescriptionTextArea;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton loadHomeButton;
	private javax.swing.JList<String> sampleHomesList;
	private javax.swing.JPanel sampleHomesPanel;
	private javax.swing.JScrollPane sampleHomesScrollPane;
	// End of variables declaration//GEN-END:variables
}
